# Change these first
owner: flash1232 # Your GitHub organization or username, where this repository lives
repo: testuptime # The name of this repository

sites:
  - name: Wordle PvP Frontend
    url: https://wordlepvp-frontend.oxv.io
  - name: Wordle PvP Backend
    url: https://wordlepvp-backend.oxv.io
    expectedStatusCodes:
      - 404
    __dangerous__body_down_if_text_missing: "Whitelabel Error Page"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.oxv.io
  #baseUrl: /testuptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Basically Wordle. Status
  theme: night
  introTitle: "Basically Wordle. Status Page"
  introMessage: Watch the current status.
  robotsText: "User-agent: * \n Disallow: /"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
